### ISSUE TITLE
Add Entry API

### ISSUE THREAD

**Issue by zbraniecki** [kardeiz/type-map#1]
I'd like to use this API for intl_memoizer in https://github.com/projectfluent/fluent-rs to replace `typemap`.

In memoizer we make use of the `Entry` API that `typemap` has. Could you add `Entry` to this crate?

[0] https://github.com/projectfluent/fluent-rs/blob/master/intl-memoizer/src/lib.rs#L42

**Comment by kardeiz** [comment]
Hi @zbraniecki, I've just added the `Entry` API in [`0.3.0`](https://crates.io/crates/type-map/0.3.0).

Closing this, but let me know if you have any issues using it!

**Comment by zbraniecki** [comment]
Yep! It works great, thank you!
