### ISSUE TITLE
Add `Assignment` container type

### ISSUE THREAD

**Issue by colelawrence** [kardeiz/type-map#3]
It would be really handy to have a way to collect multiple assignments without actually needing a `TypeMap`.

I would imagine the type looking something like the following:

```rust
pub struct AssignTypeValue(TypeId, Box<dyn Any>);

impl AssignTypeValue {
    pub fn new<T: 'static>(value: T) -> Self {
        AssignAttribute(TypeId::of::<T>(), Box::new(value))
    }
}


impl TypeMap {
    /// Insert a detached [`AssignTypeValue`] into this [`TypeMap`].
    pub fn insert_assignment(&mut self, val: AssignTypeValue) {
        self.map
            .get_or_insert_with(|| FxHashMap::default())
            .insert(val.0, val.1)
    }
}
```

This would allow me to define an interface that lets my code collect a list of assignments it wants to make, without giving it read access to the destination `TypeMap`.

I'm open to suggestions, and depending on where my current problem goes, I may fork and submit a PR.

**Comment by kardeiz** [comment]
@colelawrence Thanks for the issue! I think I can see the value of this. What if we just added a `raw_insert` (or some better name) to `TypeMap`, that would have the signature:

    pub fn raw_insert(&mut self, key: TypeId, value: Box<dyn Any>) -> Option<Box<dyn Any>>;

You could have your own `AssignTypeValue` container or just use tuples then destructure them when you did the insert. Would that work for your case?

**Comment by colelawrence** [comment]
Yeah, that would work as well!

The benefit is negligible, but by specifying a `struct RawInsert(TypeId, Box<dyn Any>);`, you can forbid the users of `TypeMap` from accidentally inserting non compatible type and value combinations through the type system–which would cause a panic upon retrieval.

If you add `raw_insert`, I'll just roll my own `RawInsert` struct to make it safer anyway for my collaborators.

**Comment by kardeiz** [comment]
@colelawrence That is a good point! I agree that would be helpful. Let me think about the name a bit (and let me know if you have suggestions). I don't especially like either `RawInsert` or `AssignedTypeValue`...

**Comment by kardeiz** [comment]
@colelawrence How about `KvPair` and `insert_kv_pair`? `tikv` uses this term for a similar container (I'm not affiliated with `tikv`; I was just looking for precedent for the term).

**Comment by colelawrence** [comment]
Sounds good to me!

**Comment by kardeiz** [comment]
Okay, I've added this in `0.5.0`. Please take a look and let me know if there is anything you would like added/changed!

**Comment by colelawrence** [comment]
Thank you, I'll try it out today and tomorrow!
